config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users do 
    resources :posts
  end

  resources :comments do
    resources :comments
  end

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'statics#index'

  get '/blog' => 'posts#index'

  get '/about' => 'statics#about'
  get '/contact' => 'statics#contact'
  get '/giving' => 'giving#index'

  # get 'users/:id' => 'users#show', as: user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable

  has_many :comments, :as => :commentable
  #validations
  validates :content, presence: true
  validates :user, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :author, class_name: "User"
	has_many :comments, as: :commentable


	validates :title,
		presence: true,
		uniqueness: true,
		length: { minimum: 5 }

	validates_presence_of :description, :image
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, foreign_key: "author_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def create
  	@commentable = find_commentable
  	@comment = @commentable.comments.build(comment_params)

  	@comment.user_id = current_user.id

  	@comment.save
  end

  def show
  end

  private
    def comment_params
    	params.require(:comment).permit(:content)
    end

    def find_commentable
	    params.each do |name, value|
	      if name =~ /(.+)_id$/
	        return $1.classify.constantize.find(value)
	      end
	    end
	    nil
	  end
end

app/controllers/giving_controller.rb
class GivingController < ApplicationController
	
	def index
		@posts = Post.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if params[:user_id]
      user = User.find(params[:user_id])
      @posts = user.posts

      # Alternate Syntax
      @posts = Post.where(:author_id => params[:user_id])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show  
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image)
    end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

	def index
	end

	def about
	end

	def contact
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title page_title
		base_title = "Andrew's Blog"
		if page_title.empty?
			base_title
		else
			base_title += " | #{page_title}"
		end
	end

	def description_meta page_description

		if page_description.empty?
			"Lorem description ipsum"
		else
			page_description
		end
	end

	def image_meta page_image

		if page_image.empty?
			"/assets/lorem_image.jpg"
		else
			page_image
		end
	end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/comments/_index.html.erb
<ol id="comments-list">
	<% object.each do |comment| %>
		<%= render '/comments/show', object: comment %>
	<% end -%>
</ol>

app/views/comments/_new.html.erb
<%= form_for [object, Comment.new], remote: true do |f| %>
  <%= f.label :content, "Escribir nuevo comentario" %><br/>
  <%= f.text_area :content, placeholder: "Esto es un comentario...", :class => "comments_textarea" %>
  <p><%= f.submit "Comentar" %></p>
<% end %>

app/views/comments/_show.html.erb
<li>
	<strong><%= object.user.email %></strong> said: <br>
	<div class='comment_<%="#{object.id}" %>' > <%= object.content %> </div>
	<div class='comment_<%="#{object.id}" %>' > <%= object.created_at.strftime("%d/%m/%Y") %> at <%= object.created_at.strftime("%H:%M") %> </div>
</li>
<!-- http://apidock.com/ruby/DateTime/strftime -->

app/views/comments/create.js.erb
// alert('<%= "Soy un comentario nuevo #{@comment.content}" %>' );
$('.comments_textarea').val('');
$('#comment_content').val('');
$('#comments-list').prepend('<%= escape_javascript(render("comments/show", object: @comment)) %>');
$('.comments-list').prepend('<%= escape_javascript(render("comments/show", object: @comment)) %>');

app/views/giving/_list.html.erb
<%= object.each do |post| %>
	<%= render "/giving/show", object: post %>
<% end -%>

app/views/giving/_show-comments.html.erb
<% object.each do |comment| %>
	Id: <%= comment.id %> <br>
	<%= comment.content %> <br>
	Commented by: <%= comment.user.email %> at: <%= comment.created_at.strftime("%T") %> <br>
<% end %>

app/views/giving/_show.html.erb
<li> Post ID: <%= object.id %> </li>
<%= object.description %> <br>
<%= object.created_at.strftime("%T") %> <br><br>

<p>Comments</p>
<%= render "/comments/new", object: object %> <br>
<div class="comments-list">
	<%= render "/giving/show-comments", object: object.comments %> <br>
</div>

app/views/giving/index.html.erb
<% provide(:title, 'Giving Exercise') %> 

<h1>Giving objects through rendering exercise</h1>

<ul>
	<%= render "/giving/list", object: @posts  %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <meta property="og:url" content="<%= request.original_url  %>">
	<meta name="author" content="Andrew Alva">
	<meta name="twitter:card" content="summary_large_image">
  	<meta name="twitter:site" content="@Andrew__Alva">
  	<meta name="twitter:creator" content="@Andrew__Alva">
	
	<meta property="og:url" content="<%= request.original_url  %>">
	<meta name='title' content='<%= full_title(yield(:title)) %>'>
	<meta property='og:title' content='<%= full_title(yield(:title)) %>'>
	<meta name='twitter:title' content='<%= full_title(yield(:title)) %>'>
	<meta name='image' content='<%= image_meta(yield(:image)) %>'>
	<meta property='og:image' content='<%= image_meta(yield(:image)) %>'>
	<meta name='twitter:image' content='<%= image_meta(yield(:image)) %>'>
	<meta name='description' content='<%= description_meta(yield(:description)) %>'>
	<meta property='og:description' content='<%= description_meta(yield(:description)) %>'>
	<meta name='twitter:description' content='<%= description_meta(yield(:description)) %>'>

	<meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body class="body-<%=yield(:title)%>">
  	<nav>
  		<ul>
  			<li><%= link_to 'Home', root_path %></li>
  			<li><%= link_to 'Blog', '/blog' %></li>
  			<li><%= link_to 'About', '/about' %></li>
        <li><%= link_to 'Contact', '/contact' %></li>
  			<li><%= link_to 'Giving', '/giving' %></li>
  		</ul>

  		<ul>
  			<%= render 'devise/menu/registration_items' %>
 			  <%= render 'devise/menu/login_items' %>
  		</ul>
  	</nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, 'Blog') %>
<% provide(:description, 'Hello world! This is Andrew Blog') %>
<% provide(:image, '/assets/share_image.jpg') %>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.image %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Post', new_post_path %>
<% end -%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% provide(:title, "#{@post.title}") %>
<% provide(:description, "#{@post.description}") %>
<% provide(:image, "#{@post.image}") %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
  <%= @post.comments %>
</p>

<p>
	<!-- Escrito por <%= link_to "#{@post.author.email}", post_path(@post) %> -->
	<!-- Escrito por <%= link_to "#{@post.author.email}", @post %> -->
	Escrito por <%= link_to "#{@post.author.email}", user_posts_path(@post.author) %>
</p>

<%= render '/comments/new', object: @post %>
<ul>
  <%= render '/comments/index', object: @post.comments %>
</ul>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/statics/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>

app/views/statics/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

app/views/statics/index.html.erb
<h1>Home</h1>